import { db } from "@/db";
import { ProductStockTypeEnum } from "@/lib/enums/ProductStockTypeEnum";
import { products } from "../schema";

export async function productSeeder() {
  const isHasRecord = (await db.$count(products)) > 0;

  if (!isHasRecord) {
    const data: (typeof products.$inferInsert)[] = [
      {
        name: "Hao Kao",
        code: "10000001",
        product_category_id: BigInt(7),
        price: "12000",
        image: "/storage/pos/food-corner/food.webp",
        fc_tenant_id: BigInt(1),
        ep_valid_term: null,
        swimming_class_valid_for: null,
        description: "Pangsit goreng isi ayam yang renyah dan gurih.",
        stock_type: ProductStockTypeEnum.NON_STOCK,
        ssr_penalty: null,
        is_rentable: false,
      },
      {
        name: "Nasi Goreng Seafood",
        code: "10000002",
        product_category_id: BigInt(1),
        price: "25000",
        image: "/storage/pos/food-corner/food.webp",
        fc_tenant_id: BigInt(2),
        ep_valid_term: null,
        swimming_class_valid_for: null,
        description: "Nasi goreng dengan aneka seafood segar dan bumbu khas.",
        stock_type: ProductStockTypeEnum.NON_STOCK,
        ssr_penalty: null,
        is_rentable: false,
      },
      {
        name: "Fried Tofu Skin",
        code: "10000003",
        product_category_id: BigInt(7),
        price: "12000",
        image: "/storage/pos/food-corner/food.webp",
        fc_tenant_id: BigInt(3),
        ep_valid_term: null,
        swimming_class_valid_for: null,
        description: "Kulit tahu goreng yang garing dengan rasa gurih.",
        stock_type: ProductStockTypeEnum.NON_STOCK,
        ssr_penalty: null,
        is_rentable: false,
      },
      {
        name: "Sate Ayam",
        code: "10000004",
        product_category_id: BigInt(1),
        price: "18000",
        image: "/storage/pos/food-corner/food.webp",
        fc_tenant_id: BigInt(1),
        ep_valid_term: null,
        swimming_class_valid_for: null,
        description: "Sate ayam dengan bumbu kacang khas Indonesia.",
        stock_type: ProductStockTypeEnum.NON_STOCK,
        ssr_penalty: null,
        is_rentable: false,
      },
      {
        name: "Rendang Daging",
        code: "10000005",
        product_category_id: BigInt(1),
        price: "30000",
        image: "/storage/pos/food-corner/food.webp",
        fc_tenant_id: BigInt(2),
        ep_valid_term: null,
        swimming_class_valid_for: null,
        description:
          "Rendang daging sapi empuk dengan bumbu rempah khas Padang.",
        stock_type: ProductStockTypeEnum.NON_STOCK,
        ssr_penalty: null,
        is_rentable: false,
      },
      {
        name: "Bakso",
        code: "10000006",
        product_category_id: BigInt(1),
        price: "15000",
        image: "/storage/pos/food-corner/food.webp",
        fc_tenant_id: BigInt(3),
        ep_valid_term: null,
        swimming_class_valid_for: null,
        description: "Bakso sapi kenyal dengan kuah kaldu gurih.",
        stock_type: ProductStockTypeEnum.NON_STOCK,
        ssr_penalty: null,
        is_rentable: false,
      },
      {
        name: "Mie Ayam",
        code: "10000007",
        product_category_id: BigInt(1),
        price: "14000",
        image: "/storage/pos/food-corner/food.webp",
        fc_tenant_id: BigInt(1),
        ep_valid_term: null,
        swimming_class_valid_for: null,
        description: "Mie ayam dengan topping ayam kecap dan pangsit goreng.",
        stock_type: ProductStockTypeEnum.NON_STOCK,
        ssr_penalty: null,
        is_rentable: false,
      },
      {
        name: "Siomay",
        code: "10000008",
        product_category_id: BigInt(7),
        price: "12000",
        image: "/storage/pos/food-corner/food.webp",
        fc_tenant_id: BigInt(2),
        ep_valid_term: null,
        swimming_class_valid_for: null,
        description: "Siomay kukus dengan saus kacang pedas manis.",
        stock_type: ProductStockTypeEnum.NON_STOCK,
        ssr_penalty: null,
        is_rentable: false,
      },
      {
        name: "Martabak Manis",
        code: "10000009",
        product_category_id: BigInt(5),
        price: "10000",
        image: "/storage/pos/food-corner/food.webp",
        fc_tenant_id: BigInt(3),
        ep_valid_term: null,
        swimming_class_valid_for: null,
        description: "Martabak manis dengan topping keju dan coklat lezat.",
        stock_type: ProductStockTypeEnum.NON_STOCK,
        ssr_penalty: null,
        is_rentable: false,
      },
      {
        name: "Es Teh Manis",
        code: "10000010",
        product_category_id: BigInt(8),
        price: "5000",
        image: "/storage/pos/food-corner/food.webp",
        fc_tenant_id: BigInt(1),
        ep_valid_term: null,
        swimming_class_valid_for: null,
        description: "Es teh manis yang segar untuk melepas dahaga.",
        stock_type: ProductStockTypeEnum.NON_STOCK,
        ssr_penalty: null,
        is_rentable: false,
      },
      {
        name: "Kacamata Renang",
        code: "10000011",
        product_category_id: BigInt(9),
        price: "25000",
        image: "/storage/pos/souvenir/souvenir.png",
        fc_tenant_id: null,
        ep_valid_term: null,
        swimming_class_valid_for: null,
        description:
          "Kacamata renang anti kabut dengan perlindungan UV untuk kenyamanan saat berenang.",
        stock_type: ProductStockTypeEnum.STOCK,
        ssr_penalty: null,
        is_rentable: false,
      },
      {
        name: "Pelampung Anak",
        code: "10000012",
        product_category_id: BigInt(10),
        price: "30000",
        image: "/storage/pos/souvenir/souvenir.png",
        fc_tenant_id: null,
        ep_valid_term: null,
        swimming_class_valid_for: null,
        description:
          "Pelampung berbentuk cincin dengan desain menarik untuk anak-anak, membantu mereka tetap aman di air.",
        stock_type: ProductStockTypeEnum.STOCK,
        ssr_penalty: null,
        is_rentable: false,
      },
      {
        name: "Handuk Microfiber",
        code: "10000013",
        product_category_id: BigInt(11),
        price: "40000",
        image: "/storage/pos/souvenir/souvenir.png",
        fc_tenant_id: null,
        ep_valid_term: null,
        swimming_class_valid_for: null,
        description:
          "Handuk cepat kering berbahan microfiber, ringan dan mudah dibawa untuk aktivitas berenang.",
        stock_type: ProductStockTypeEnum.STOCK,
        ssr_penalty: null,
        is_rentable: false,
      },
      {
        name: "Sunblock SPF 50",
        code: "10000014",
        product_category_id: BigInt(12),
        price: "35000",
        image: "/storage/pos/souvenir/souvenir.png",
        fc_tenant_id: null,
        ep_valid_term: null,
        swimming_class_valid_for: null,
        description:
          "Tabir surya dengan SPF 50 untuk melindungi kulit dari sinar matahari saat berenang di luar ruangan.",
        stock_type: ProductStockTypeEnum.STOCK,
        ssr_penalty: null,
        is_rentable: false,
      },
      {
        name: "Kelas Renang Private",
        code: "10000015",
        product_category_id: BigInt(13),
        price: "950000",
        image: "",
        fc_tenant_id: null,
        ep_valid_term: null,
        swimming_class_valid_for: 8,
        description:
          "Pelatihan renang satu-satu dengan instruktur profesional untuk meningkatkan keterampilan renang secara personal",
        stock_type: ProductStockTypeEnum.NON_STOCK,
        ssr_penalty: null,
        is_rentable: false,
        is_required_tax: false,
      },
      {
        name: "Kelas Renang Double",
        code: "10000016",
        product_category_id: BigInt(13),
        price: "1560000",
        image: "",
        fc_tenant_id: null,
        ep_valid_term: null,
        swimming_class_valid_for: 8,
        description:
          " Sesi renang untuk dua orang, ideal bagi pasangan atau teman yang ingin belajar bersama dengan bimbingan instruktur",
        stock_type: ProductStockTypeEnum.NON_STOCK,
        ssr_penalty: null,
        is_rentable: false,
        is_required_tax: false,
      },
      {
        name: "Kelas Renang Kelompok",
        code: "10000017",
        product_category_id: BigInt(13),
        price: "2560000",
        image: "",
        fc_tenant_id: null,
        ep_valid_term: null,
        swimming_class_valid_for: 8,
        description:
          "Kelas renang untuk beberapa peserta dalam satu sesi, cocok untuk pembelajaran bersama dengan suasana yang lebih interaktif",
        stock_type: ProductStockTypeEnum.NON_STOCK,
        ssr_penalty: null,
        is_rentable: false,
        is_required_tax: false,
      },
      {
        name: "Yearly Pass",
        code: "10000018",
        product_category_id: BigInt(14),
        price: "750000",
        image: "",
        fc_tenant_id: null,
        ep_valid_term: 365,
        swimming_class_valid_for: null,
        description: "Entry pass dengan masa berlaku hingga 1 tahun",
        stock_type: ProductStockTypeEnum.NON_STOCK,
        ssr_penalty: null,
        is_rentable: false,
        is_required_tax: false,
      },
      {
        name: "Weekly Pass",
        code: "10000019",
        product_category_id: BigInt(14),
        price: "150000",
        image: "",
        fc_tenant_id: null,
        ep_valid_term: 7,
        swimming_class_valid_for: 8,
        description: "Entry pass dengan masa berlaku hingga 1 minggu",
        stock_type: ProductStockTypeEnum.NON_STOCK,
        ssr_penalty: null,
        is_rentable: false,
        is_required_tax: false,
      },
      {
        name: "Celana Anak",
        code: "10000020",
        product_category_id: BigInt(9),
        price: "40000",
        image: "/storage/swimsuit-rent/celana-anak.png",
        fc_tenant_id: null,
        ep_valid_term: null,
        swimming_class_valid_for: null,
        description: "Celana renang untuk ukuran anak anak",
        stock_type: ProductStockTypeEnum.STOCK,
        ssr_penalty: "120000",
        is_rentable: true,
        is_required_tax: false,
      },
      {
        name: "Celana Dewasa",
        code: "10000021",
        product_category_id: BigInt(9),
        price: "60000",
        image: "/storage/swimsuit-rent/celana-dewasa.png",
        fc_tenant_id: null,
        ep_valid_term: null,
        swimming_class_valid_for: null,
        description: "Celana renang untuk ukuran remaja hingga dewasa",
        stock_type: ProductStockTypeEnum.STOCK,
        ssr_penalty: "120000",
        is_rentable: true,
        is_required_tax: false,
      },
      {
        name: "DVG Dewasa",
        code: "10000022",
        product_category_id: BigInt(9),
        price: "60000",
        image: "/storage/swimsuit-rent/dvg-dewasa.png",
        fc_tenant_id: null,
        ep_valid_term: null,
        swimming_class_valid_for: null,
        description: "Baju renang set untuk remaja hingga dewasa",
        stock_type: ProductStockTypeEnum.STOCK,
        ssr_penalty: "120000",
        is_rentable: true,
        is_required_tax: false,
      },
      {
        name: "Har Gow",
        code: "10000023",
        product_category_id: BigInt(17),
        price: "15000",
        image: "/storage/pos/food-corner/food.webp",
        fc_tenant_id: null,
        ep_valid_term: null,
        swimming_class_valid_for: null,
        description: "Dumpling udang dengan kulit tipis dan transparan.",
        stock_type: ProductStockTypeEnum.NON_STOCK,
        ssr_penalty: null,
        is_rentable: false,
      },
      {
        name: "Cheung Fun",
        code: "10000024",
        product_category_id: BigInt(17),
        price: "12000",
        image: "/storage/pos/food-corner/food.webp",
        fc_tenant_id: null,
        ep_valid_term: null,
        swimming_class_valid_for: null,
        description: "Lembaran mi beras yang lembut diisi udang atau daging.",
        stock_type: ProductStockTypeEnum.NON_STOCK,
        ssr_penalty: null,
        is_rentable: false,
      },
      {
        name: "Egg Tart",
        code: "10000025",
        product_category_id: BigInt(17),
        price: "10000",
        image: "/storage/pos/food-corner/food.webp",
        fc_tenant_id: null,
        ep_valid_term: null,
        swimming_class_valid_for: null,
        description: "Kue tart telur dengan kulit renyah dan isian lembut.",
        stock_type: ProductStockTypeEnum.NON_STOCK,
        ssr_penalty: null,
        is_rentable: false,
      },
      {
        name: "Loker Standar",
        code: "10000026",
        product_category_id: BigInt(15),
        price: "20000",
        image: "",
        fc_tenant_id: null,
        description: "Standar",
        stock_type: ProductStockTypeEnum.NON_STOCK,
        is_rentable: false,
        is_required_tax: false,
      },
      {
        name: "Loker Family",
        code: "10000027",
        product_category_id: BigInt(15),
        price: "30000",
        image: "",
        fc_tenant_id: null,
        description: "Family",
        stock_type: ProductStockTypeEnum.NON_STOCK,
        is_rentable: false,
        is_required_tax: false,
      },
      {
        name: "Tiket Anak/Dewasa Weekday",
        code: "10000028",
        product_category_id: BigInt(18),
        price: "60000",
        image: "",
        fc_tenant_id: null,
        description: "Anak/Dewasa",
        stock_type: ProductStockTypeEnum.NON_STOCK,
        is_rentable: false,
      },
      {
        name: "Tiket Anak/Dewasa Weekend",
        code: "10000029",
        product_category_id: BigInt(18),
        price: "100000",
        image: "",
        fc_tenant_id: null,
        description: "Anak/Dewasa",
        stock_type: ProductStockTypeEnum.NON_STOCK,
        is_rentable: false,
      },
      {
        name: "Tiket Online",
        code: "10000030",
        product_category_id: BigInt(18),
        price: "0",
        image: "",
        fc_tenant_id: null,
        description: "Anak/Dewasa",
        stock_type: ProductStockTypeEnum.NON_STOCK,
        is_rentable: false,
        ssr_penalty: null,
      },
      {
        name: "Special Item",
        code: "10000031",
        product_category_id: BigInt(21),
        price: "0",
        image: "/assets/imgs/logo.png",
        fc_tenant_id: null,
        ep_valid_term: null,
        swimming_class_valid_for: null,
        description: "Resto Special Item",
        stock_type: ProductStockTypeEnum.NON_STOCK,
        ssr_penalty: null,
      },
      {
        name: "Wristband",
        code: "10000032",
        product_category_id: BigInt(19),
        price: "25000",
        image: "",
        fc_tenant_id: null,
        description: "Gelang",
        stock_type: ProductStockTypeEnum.NON_STOCK,
        is_rentable: false,
        is_required_tax: false,
        is_discountable: false,
      },
      {
        name: "Gazebo Family",
        code: "10000033",
        product_category_id: BigInt(16),
        price: "200000",
        image: "",
        fc_tenant_id: null,
        description: "Family",
        stock_type: ProductStockTypeEnum.NON_STOCK,
        is_rentable: false,
        is_required_tax: false,
      },
      {
        name: "Gazebo VIP",
        code: "10000034",
        product_category_id: BigInt(16),
        price: "400000",
        image: "",
        fc_tenant_id: null,
        description: "VIP",
        stock_type: ProductStockTypeEnum.NON_STOCK,
        is_rentable: false,
        is_required_tax: false,
      },
      {
        name: "Aqua Botol",
        code: "10000035",
        product_category_id: BigInt(8),
        price: "5000",
        image: "/storage/pos/food-corner/food.webp",
        fc_tenant_id: BigInt(2),
        ep_valid_term: null,
        swimming_class_valid_for: null,
        description: "Aqua botol ukuran 500ml",
        stock_type: ProductStockTypeEnum.STOCK,
        ssr_penalty: null,
        is_rentable: false,
      },
      {
        name: "Top Up",
        code: "10000036",
        product_category_id: BigInt(20),
        price: "10000",
        image: "",
        fc_tenant_id: null,
        ep_valid_term: null,
        swimming_class_valid_for: null,
        description: "CashQ",
        stock_type: ProductStockTypeEnum.NON_STOCK,
        ssr_penalty: null,
        is_rentable: false,
        is_required_tax: false,
        is_discountable: false,
      },
      {
        name: "Tiket Anak-Anak < 80cm",
        code: "10000037",
        product_category_id: BigInt(18),
        price: "0",
        image: "",
        fc_tenant_id: null,
        description: "Anak-anak <80cm",
        stock_type: ProductStockTypeEnum.NON_STOCK,
        is_rentable: false,
      },
      {
        name: "Tiket Lansia > 70 Tahun",
        code: "10000038",
        product_category_id: BigInt(18),
        price: "0",
        image: "",
        fc_tenant_id: null,
        description: "Lansia > 70 Tahun",
        stock_type: ProductStockTypeEnum.NON_STOCK,
        is_rentable: false,
      },
    ];

    await Promise.all(
      data.map((dataItem) =>
        db.insert(products).values(dataItem).onDuplicateKeyUpdate({
          set: dataItem,
        }),
      ),
    );
  }
}
