import { PermissionEnum } from "@/lib/enums/PermissionEnum";

export const patioCashierPermissions = [
  PermissionEnum.RESTO_PATIO_SALES_RECEIPT,
  PermissionEnum.RESTO_PATIO_SALES_PRINT_RECEIPT,
  PermissionEnum.RESTO_PATIO_CAPTAIN_ORDER_INDEX,
  PermissionEnum.RESTO_PATIO_CAPTAIN_ORDER_SHOW,
  PermissionEnum.RESTO_PATIO_CAPTAIN_ORDER_CREATE,
  PermissionEnum.RESTO_PATIO_CAPTAIN_ORDER_STORE,
  PermissionEnum.RESTO_PATIO_CAPTAIN_ORDER_EDIT,
  PermissionEnum.RESTO_PATIO_CAPTAIN_ORDER_UPDATE,
  PermissionEnum.RESTO_PATIO_CAPTAIN_ORDER_BILL,
  PermissionEnum.RESTO_PATIO_CAPTAIN_ORDER_PRINT_BILL,
  PermissionEnum.RESTO_PATIO_CAPTAIN_ORDER_KITCHEN,
  PermissionEnum.RESTO_PATIO_CAPTAIN_ORDER_PRINT_KITCHEN,
  PermissionEnum.RESTO_PATIO_CAPTAIN_ORDER_TABLE_CHECK,
  PermissionEnum.RESTO_PATIO_CAPTAIN_ORDER_PRINT_TABLE_CHECK,

  PermissionEnum.RESTO_PATIO_SALES_CREATE,
  PermissionEnum.RESTO_PATIO_SALES_STORE,

  PermissionEnum.SALES_INDEX,
  PermissionEnum.SALES_VOID,
  PermissionEnum.SALES_REPRINT,

  PermissionEnum.SUPPORT_TICKET_STORE,
];
