import { PermissionEnum } from "@/lib/enums/PermissionEnum";

export const locker3Permissions = [
  PermissionEnum.CASHQ_TRANSACTION_INDEX,
  PermissionEnum.CASHQ_TRANSACTION_TOP_UP_CREATE,
  PermissionEnum.CASHQ_TRANSACTION_TOP_UP_STORE,
  PermissionEnum.CASHQ_TRANSACTION_TOP_UP_RECEIPT,
  PermissionEnum.CASHQ_TRANSACTION_TOP_UP_PRINT_RECEIPT,

  PermissionEnum.CASHQ_TRANSACTION_LOCKER_RENT_INDEX,
  PermissionEnum.CASHQ_TRANSACTION_LOCKER_RENT_CREATE,
  PermissionEnum.CASHQ_TRANSACTION_LOCKER_RENT_STORE,
  PermissionEnum.CASHQ_TRANSACTION_LOCKER_RENT_EDIT,
  PermissionEnum.CASHQ_TRANSACTION_LOCKER_RENT_UPDATE,
  PermissionEnum.CASHQ_TRANSACTION_LOCKER_RENT_RECEIPT,
  PermissionEnum.CASHQ_TRANSACTION_LOCKER_RENT_PRINT_RECEIPT,

  PermissionEnum.CASHQ_TRANSACTION_HISTORY_SHOW,
  PermissionEnum.CASHQ_TRANSACTION_BINDING_CASHQ_INDEX,
  PermissionEnum.CASHQ_TRANSACTION_BINDING_CASHQ_CREATE,
  PermissionEnum.CASHQ_TRANSACTION_BINDING_CASHQ_STORE,
  PermissionEnum.CASHQ_TRANSACTION_BINDING_CASHQ_RECEIPT,
  PermissionEnum.CASHQ_TRANSACTION_BINDING_CASHQ_PRINT_RECEIPT,

  PermissionEnum.CASHQ_TRANSACTION_GAZEBO_RENT_INDEX,
  PermissionEnum.CASHQ_TRANSACTION_GAZEBO_RENT_CREATE,
  PermissionEnum.CASHQ_TRANSACTION_GAZEBO_RENT_STORE,
  PermissionEnum.CASHQ_TRANSACTION_GAZEBO_RENT_EDIT,
  PermissionEnum.CASHQ_TRANSACTION_GAZEBO_RENT_UPDATE,
  PermissionEnum.CASHQ_TRANSACTION_GAZEBO_RENT_RECEIPT,
  PermissionEnum.CASHQ_TRANSACTION_GAZEBO_RENT_PRINT_RECEIPT,

  PermissionEnum.CASHQ_TRANSACTION_VOID,

  PermissionEnum.SWIMSUIT_RENT_SALES_CREATE,
  PermissionEnum.SWIMSUIT_RENT_SALES_STORE,
  PermissionEnum.SWIMSUIT_RENT_SALES_RECEIPT,
  PermissionEnum.SWIMSUIT_RENT_SALES_PRINT_RECEIPT,
  PermissionEnum.SWIMSUIT_RENT_RETURN_INDEX,
  PermissionEnum.SWIMSUIT_RENT_RETURN_SHOW,

  PermissionEnum.LOCKER_SALES_CREATE,
  PermissionEnum.LOCKER_SALES_STORE,
  PermissionEnum.LOCKER_SALES_RECEIPT,
  PermissionEnum.LOCKER_SALES_PRINT_RECEIPT,

  PermissionEnum.WRISTBAND_RENT_WALLET_CREATE,
  PermissionEnum.WRISTBAND_RENT_WALLET_STORE,
  PermissionEnum.WRISTBAND_RENT_WALLET_RECEIPT,
  PermissionEnum.WRISTBAND_RENT_WALLET_PRINT_RECEIPT,

  PermissionEnum.SALES_INDEX,
  PermissionEnum.SALES_VOID,
  PermissionEnum.SALES_REPRINT,

  PermissionEnum.SUPPORT_TICKET_STORE,
];
