import { PermissionEnum } from "@/lib/enums/PermissionEnum";

export const refund3Permissions = [
  PermissionEnum.CASHQ_TRANSACTION_INDEX,

  PermissionEnum.CASHQ_TRANSACTION_REFUND_WRISTBAND_SHOW,
  PermissionEnum.CASHQ_TRANSACTION_REFUND_WRISTBAND_UPDATE_WRISTBAND_STATUS,
  PermissionEnum.CASHQ_TRANSACTION_REFUND_WRISTBAND_UPDATE_DEPOSIT_WITHDRAW_LOST_DAMAGED,
  PermissionEnum.CASHQ_TRANSACTION_REFUND_WRISTBAND_UPDATE_DEPOSIT_WITHDRAW,
  PermissionEnum.CASHQ_TRANSACTION_REFUND_WRISTBAND_UPDATE_SALDO_WITHDRAW,
  PermissionEnum.CASHQ_TRANSACTION_REFUND_WRISTBAND_RECEIPT_DEPOSIT_WITHDRAW,
  PermissionEnum.CASHQ_TRANSACTION_REFUND_WRISTBAND_RECEIPT_LOST_DAMAGED,
  PermissionEnum.CASHQ_TRANSACTION_REFUND_WRISTBAND_PRINT_RECEIPT,

  PermissionEnum.CASHQ_TRANSACTION_VOID,
  PermissionEnum.CASHQ_TRANSACTION_HISTORY_SHOW,

  PermissionEnum.SALES_INDEX,
  PermissionEnum.SALES_VOID,
  PermissionEnum.SALES_REPRINT,

  PermissionEnum.SUPPORT_TICKET_STORE,
];
